roles = ["frontend", "backend"]
auth_callback_path = ["/api/auth/shopify/callback"]
webhooks_path = "/api/webhooks/shopify"
port = 3000

[commands]
dev = "npm run dev -- --port 3000"
build = "npm run build"
