/**
 * Synthetic Shopify pull for the demo video.
 *
 * This is not merchant data. It is shaped like the kind of Shopify data Synapse
 * will collect so the demo can show a realistic store story before real users
 * connect their shops.
 */
export const SYNTHETIC_SHOPIFY_PULL = {
  generated_at: "2026-06-06T16:30:00.000Z",
  source: "synthetic_demo_shopify",
  shop: {
    name: "Luma & Lane",
    domain: "luma-lane-demo.myshopify.com",
    currency: "GBP",
    category: "DTC skincare",
    tagline: "Barrier-first skincare for busy women.",
  },
  windows: {
    current: {
      label: "Week of 1 June 2026",
      start: "2026-06-01",
      end: "2026-06-08",
    },
    previous: {
      label: "Week of 25 May 2026",
      start: "2026-05-25",
      end: "2026-06-01",
    },
  },
  summary: {
    revenue: { current: 18420, previous: 13280, change_pct: 38.7 },
    orders: { current: 312, previous: 228, change_pct: 36.8 },
    average_order_value: { current: 59.04, previous: 58.25, change_pct: 1.4 },
    sessions: { current: 12640, previous: 11120, change_pct: 13.7 },
    conversion_rate: { current: 0.0247, previous: 0.0205, change_pct: 20.5 },
    new_customers: { current: 196, previous: 132, change_pct: 48.5 },
    returning_customer_rate: { current: 0.371, previous: 0.421, change_pct: -11.9 },
  },
  channels: [
    {
      name: "TikTok organic",
      new_customer_share: 0.31,
      previous_new_customer_share: 0.12,
      revenue: 5850,
      orders: 96,
      note: "Three creator-style morning routine clips drove the spike.",
    },
    {
      name: "Instagram Reels",
      new_customer_share: 0.26,
      previous_new_customer_share: 0.22,
      revenue: 4680,
      orders: 78,
      note: "Product demo Reels kept working after last week's post cadence.",
    },
    {
      name: "Email",
      new_customer_share: 0.13,
      previous_new_customer_share: 0.18,
      revenue: 3010,
      orders: 52,
      note: "Strong revenue, but mostly returning buyers.",
    },
    {
      name: "Google organic",
      new_customer_share: 0.18,
      previous_new_customer_share: 0.21,
      revenue: 2640,
      orders: 44,
      note: "Stable search demand around acne patches and barrier repair.",
    },
    {
      name: "Meta ads",
      new_customer_share: 0.03,
      previous_new_customer_share: 0.11,
      revenue: 440,
      orders: 7,
      ad_spend: 520,
      roas: 0.85,
      note: "Spend is still live, but it is now the worst-performing channel.",
    },
  ],
  products: [
    {
      id: "gid://shopify/Product/1001",
      title: "GlowPatch Acne Dots",
      sku: "LL-GLOWPATCH-36",
      price: 9,
      units_sold: 790,
      previous_units_sold: 310,
      revenue: 7110,
      previous_revenue: 2790,
      inventory: 410,
      weeks_of_stock_left: 0.5,
      note: "Went viral on TikTok; stockout risk is immediate.",
    },
    {
      id: "gid://shopify/Product/1002",
      title: "Cloud Cleanser",
      sku: "LL-CLOUD-CLEANSER",
      price: 20,
      units_sold: 188,
      previous_units_sold: 176,
      revenue: 3760,
      previous_revenue: 3520,
      inventory: 940,
      weeks_of_stock_left: 5.0,
      note: "Reliable basket builder, often bought with GlowPatch.",
    },
    {
      id: "gid://shopify/Product/1003",
      title: "Skin Barrier Mist",
      sku: "LL-BARRIER-MIST",
      price: 22.5,
      units_sold: 142,
      previous_units_sold: 118,
      revenue: 3195,
      previous_revenue: 2655,
      inventory: 280,
      weeks_of_stock_left: 2.0,
      note: "Improving after Instagram demos.",
    },
    {
      id: "gid://shopify/Product/1004",
      title: "Overnight Rescue Balm",
      sku: "LL-RESCUE-BALM",
      price: 30,
      units_sold: 90,
      previous_units_sold: 94,
      revenue: 2700,
      previous_revenue: 2820,
      inventory: 620,
      weeks_of_stock_left: 6.9,
      note: "High AOV, but no growth this week.",
    },
    {
      id: "gid://shopify/Product/1005",
      title: "Weekend Reset Kit",
      sku: "LL-RESET-KIT",
      price: 48,
      units_sold: 22,
      previous_units_sold: 41,
      revenue: 1056,
      previous_revenue: 1968,
      inventory: 360,
      weeks_of_stock_left: 16.4,
      note: "Bundle is fading; dead-stock risk if not repositioned.",
    },
    {
      id: "gid://shopify/Product/1006",
      title: "Mini Travel Trio",
      sku: "LL-TRAVEL-TRIO",
      price: 24,
      units_sold: 0,
      previous_units_sold: 3,
      revenue: 0,
      previous_revenue: 72,
      inventory: 510,
      weeks_of_stock_left: null,
      note: "No sales despite inventory; hide from homepage.",
    },
  ],
  sample_orders: [
    {
      order_id: 60241,
      name: "#LL-60241",
      created_at: "2026-06-01T09:14:22Z",
      customer_type: "new",
      source: "TikTok organic",
      total_price: 58,
      line_items: [
        { product_title: "GlowPatch Acne Dots", quantity: 4, price: 9 },
        { product_title: "Cloud Cleanser", quantity: 1, price: 20 },
        { product_title: "Skin Barrier Mist", quantity: 1, price: 22 },
      ],
    },
    {
      order_id: 60258,
      name: "#LL-60258",
      created_at: "2026-06-01T18:42:11Z",
      customer_type: "returning",
      source: "Email",
      total_price: 78,
      line_items: [
        { product_title: "Overnight Rescue Balm", quantity: 1, price: 30 },
        { product_title: "Weekend Reset Kit", quantity: 1, price: 48 },
      ],
    },
    {
      order_id: 60304,
      name: "#LL-60304",
      created_at: "2026-06-02T11:08:47Z",
      customer_type: "new",
      source: "TikTok organic",
      total_price: 45,
      line_items: [{ product_title: "GlowPatch Acne Dots", quantity: 5, price: 9 }],
    },
    {
      order_id: 60377,
      name: "#LL-60377",
      created_at: "2026-06-03T20:16:05Z",
      customer_type: "new",
      source: "Instagram Reels",
      total_price: 72,
      line_items: [
        { product_title: "GlowPatch Acne Dots", quantity: 3, price: 9 },
        { product_title: "Cloud Cleanser", quantity: 1, price: 20 },
        { product_title: "Skin Barrier Mist", quantity: 1, price: 25 },
      ],
    },
    {
      order_id: 60433,
      name: "#LL-60433",
      created_at: "2026-06-04T15:33:59Z",
      customer_type: "new",
      source: "Meta ads",
      total_price: 39,
      line_items: [
        { product_title: "GlowPatch Acne Dots", quantity: 1, price: 9 },
        { product_title: "Overnight Rescue Balm", quantity: 1, price: 30 },
      ],
    },
    {
      order_id: 60518,
      name: "#LL-60518",
      created_at: "2026-06-05T13:51:20Z",
      customer_type: "new",
      source: "TikTok organic",
      total_price: 90,
      line_items: [{ product_title: "GlowPatch Acne Dots", quantity: 10, price: 9 }],
    },
  ],
  synthetic_growth_brief: {
    week_of: "Week of 1 June 2026",
    headline_numbers: [
      { label: "Revenue", value: "GBP 18.4k, up 39% WoW", direction: "up" },
      { label: "Orders", value: "312, up 37% WoW", direction: "up" },
      { label: "Conversion", value: "2.47%, up from 2.05%", direction: "up" },
    ],
    whats_working:
      "TikTok organic created the breakout. It jumped from 12% to 31% of new customers and drove GBP 5.9k in revenue. GlowPatch Acne Dots are the product carrying the week: 790 units sold, GBP 7.1k revenue, and most high-volume orders came from TikTok clips.",
    what_to_cut:
      "Meta ads are the clean cut. They spent GBP 520 for GBP 440 revenue, only 7 orders, and just 3% of new customers. Keep that budget away from Meta until the TikTok stockout risk is handled.",
    one_move: {
      action: "Reorder GlowPatch today and move Meta's GBP 520 into TikTok creator seeding.",
      rationale:
        "GlowPatch has about half a week of stock left while TikTok is producing the best new-customer growth. If it sells out, the channel that just caused the revenue spike has nothing to sell.",
    },
  },
};
