/**
 * Synthetic Shopify pull for the demo video.
 *
 * This is not merchant data. It is shaped like the kind of Shopify data Synapse
 * will collect so the demo can show a realistic store story before real users
 * connect their shops.
 */
export const SYNTHETIC_SHOPIFY_PULL = {
  generated_at: "2026-06-06T16:30:00.000Z",
  source: "synthetic_demo_shopify",
  shop: {
    name: "Luma & Lane",
    domain: "luma-lane-demo.myshopify.com",
    currency: "GBP",
    category: "DTC skincare",
    tagline: "Barrier-first skincare for busy women.",
  },
  windows: {
    current: {
      label: "Week of 1 June 2026",
      start: "2026-06-01",
      end: "2026-06-08",
    },
    previous: {
      label: "Week of 25 May 2026",
      start: "2026-05-25",
      end: "2026-06-01",
    },
  },
  summary: {
    revenue: { current: 18420, previous: 13280, change_pct: 38.7 },
    orders: { current: 312, previous: 228, change_pct: 36.8 },
    average_order_value: { current: 59.04, previous: 58.25, change_pct: 1.4 },
    sessions: { current: 12640, previous: 11120, change_pct: 13.7 },
    conversion_rate: { current: 0.0247, previous: 0.0205, change_pct: 20.5 },
    new_customers: { current: 196, previous: 132, change_pct: 48.5 },
    returning_customer_rate: { current: 0.371, previous: 0.421, change_pct: -11.9 },
  },
  channels: [
    {
      name: "TikTok organic",
      new_customer_share: 0.31,
      previous_new_customer_share: 0.12,
      revenue: 5850,
      orders: 96,
      note: "Three creator-style morning routine clips drove the spike.",
    },
    {
      name: "Instagram Reels",
      new_customer_share: 0.26,
      previous_new_customer_share: 0.22,
      revenue: 4680,
      orders: 78,
      note: "Product demo Reels kept working after last week's post cadence.",
    },
    {
      name: "Email",
      new_customer_share: 0.13,
      previous_new_customer_share: 0.18,
      revenue: 3010,
      orders: 52,
      note: "Strong revenue, but mostly returning buyers.",
    },
    {
      name: "Google organic",
      new_customer_share: 0.18,
      previous_new_customer_share: 0.21,
      revenue: 2640,
      orders: 44,
      note: "Stable search demand around acne patches and barrier repair.",
    },
    {
      name: "Meta ads",
      new_customer_share: 0.03,
      previous_new_customer_share: 0.11,
      revenue: 440,
      orders: 7,
      ad_spend: 520,
      roas: 0.85,
      note: "Spend is still live, but it is now the worst-performing channel.",
    },
  ],
  products: [
    {
      id: "gid://shopify/Product/1001",
      title: "GlowPatch Acne Dots",
      sku: "LL-GLOWPATCH-36",
      price: 9,
      units_sold: 790,
      previous_units_sold: 310,
      revenue: 7110,
      previous_revenue: 2790,
      inventory: 410,
      weeks_of_stock_left: 0.5,
      note: "Went viral on TikTok; stockout risk is immediate.",
    },
    {
      id: "gid://shopify/Product/1002",
      title: "Cloud Cleanser",
      sku: "LL-CLOUD-CLEANSER",
      price: 20,
      units_sold: 188,
      previous_units_sold: 176,
      revenue: 3760,
      previous_revenue: 3520,
      inventory: 940,
      weeks_of_stock_left: 5.0,
      note: "Reliable basket builder, often bought with GlowPatch.",
    },
    {
      id: "gid://shopify/Product/1003",
      title: "Skin Barrier Mist",
      sku: "LL-BARRIER-MIST",
      price: 22.5,
      units_sold: 142,
      previous_units_sold: 118,
      revenue: 3195,
      previous_revenue: 2655,
      inventory: 280,
      weeks_of_stock_left: 2.0,
      note: "Improving after Instagram demos.",
    },
    {
      id: "gid://shopify/Product/1004",
      title: "Overnight Rescue Balm",
      sku: "LL-RESCUE-BALM",
      price: 30,
      units_sold: 90,
      previous_units_sold: 94,
      revenue: 2700,
      previous_revenue: 2820,
      inventory: 620,
      weeks_of_stock_left: 6.9,
      note: "High AOV, but no growth this week.",
    },
    {
      id: "gid://shopify/Product/1005",
      title: "Weekend Reset Kit",
      sku: "LL-RESET-KIT",
      price: 48,
      units_sold: 22,
      previous_units_sold: 41,
      revenue: 1056,
      previous_revenue: 1968,
      inventory: 360,
      weeks_of_stock_left: 16.4,
      note: "Bundle is fading; dead-stock risk if not repositioned.",
    },
    {
      id: "gid://shopify/Product/1006",
      title: "Mini Travel Trio",
      sku: "LL-TRAVEL-TRIO",
      price: 24,
      units_sold: 0,
      previous_units_sold: 3,
      revenue: 0,
      previous_revenue: 72,
      inventory: 510,
      weeks_of_stock_left: null,
      note: "No sales despite inventory; hide from homepage.",
    },
  ],
  sample_orders: [
    {
      order_id: 60241,
      name: "#LL-60241",
      created_at: "2026-06-01T09:14:22Z",
      customer_type: "new",
      source: "TikTok organic",
      total_price: 58,
      line_items: [
        { product_title: "GlowPatch Acne Dots", quantity: 4, price: 9 },
        { product_title: "Cloud Cleanser", quantity: 1, price: 20 },
        { product_title: "Skin Barrier Mist", quantity: 1, price: 22 },
      ],
    },
    {
      order_id: 60258,
      name: "#LL-60258",
      created_at: "2026-06-01T18:42:11Z",
      customer_type: "returning",
      source: "Email",
      total_price: 78,
      line_items: [
        { product_title: "Overnight Rescue Balm", quantity: 1, price: 30 },
        { product_title: "Weekend Reset Kit", quantity: 1, price: 48 },
      ],
    },
    {
      order_id: 60304,
      name: "#LL-60304",
      created_at: "2026-06-02T11:08:47Z",
      customer_type: "new",
      source: "TikTok organic",
      total_price: 45,
      line_items: [{ product_title: "GlowPatch Acne Dots", quantity: 5, price: 9 }],
    },
    {
      order_id: 60377,
      name: "#LL-60377",
      created_at: "2026-06-03T20:16:05Z",
      customer_type: "new",
      source: "Instagram Reels",
      total_price: 72,
      line_items: [
        { product_title: "GlowPatch Acne Dots", quantity: 3, price: 9 },
        { product_title: "Cloud Cleanser", quantity: 1, price: 20 },
        { product_title: "Skin Barrier Mist", quantity: 1, price: 25 },
      ],
    },
    {
      order_id: 60433,
      name: "#LL-60433",
      created_at: "2026-06-04T15:33:59Z",
      customer_type: "new",
      source: "Meta ads",
      total_price: 39,
      line_items: [
        { product_title: "GlowPatch Acne Dots", quantity: 1, price: 9 },
        { product_title: "Overnight Rescue Balm", quantity: 1, price: 30 },
      ],
    },
    {
      order_id: 60518,
      name: "#LL-60518",
      created_at: "2026-06-05T13:51:20Z",
      customer_type: "new",
      source: "TikTok organic",
      total_price: 90,
      line_items: [{ product_title: "GlowPatch Acne Dots", quantity: 10, price: 9 }],
    },
  ],
  analytics_catalog: [
    {
      group: "Revenue",
      label: "Gross sales",
      value: "GBP 19.6k",
      delta: "+41% WoW",
      source: "Orders",
      insight: "Topline demand accelerated before refunds and discounts.",
      x: 18,
      y: 18,
      tone: "up",
    },
    {
      group: "Revenue",
      label: "Net revenue",
      value: "GBP 18.4k",
      delta: "+39% WoW",
      source: "Orders",
      insight: "Actual recognised Shopify revenue for the week.",
      x: 28,
      y: 10,
      tone: "up",
    },
    {
      group: "Revenue",
      label: "Refunds",
      value: "GBP 420",
      delta: "-8% WoW",
      source: "Orders",
      insight: "Refund pressure is not causing the growth story.",
      x: 39,
      y: 17,
      tone: "neutral",
    },
    {
      group: "Revenue",
      label: "Discounts",
      value: "GBP 790",
      delta: "+6% WoW",
      source: "Discounts",
      insight: "Growth is not being bought by heavy promotion.",
      x: 17,
      y: 34,
      tone: "neutral",
    },
    {
      group: "Orders",
      label: "Orders",
      value: "312",
      delta: "+37% WoW",
      source: "Orders",
      insight: "Order volume rose nearly as quickly as revenue.",
      x: 30,
      y: 30,
      tone: "up",
    },
    {
      group: "Orders",
      label: "AOV",
      value: "GBP 59.04",
      delta: "+1% WoW",
      source: "Orders",
      insight: "Growth is volume-led, not basket-size-led.",
      x: 43,
      y: 34,
      tone: "neutral",
    },
    {
      group: "Orders",
      label: "Units sold",
      value: "1,232",
      delta: "+62% WoW",
      source: "Line items",
      insight: "Unit velocity is rising faster than order count.",
      x: 10,
      y: 52,
      tone: "up",
    },
    {
      group: "Orders",
      label: "Items/order",
      value: "3.9",
      delta: "+18% WoW",
      source: "Line items",
      insight: "GlowPatch multi-unit orders are lifting basket density.",
      x: 24,
      y: 49,
      tone: "up",
    },
    {
      group: "Customers",
      label: "New customers",
      value: "196",
      delta: "+49% WoW",
      source: "Customers",
      insight: "The week is acquisition-led.",
      x: 56,
      y: 12,
      tone: "up",
    },
    {
      group: "Customers",
      label: "Returning rate",
      value: "37.1%",
      delta: "-5 pts",
      source: "Customers",
      insight: "Returning share fell because new customers surged.",
      x: 69,
      y: 18,
      tone: "neutral",
    },
    {
      group: "Customers",
      label: "Repeat buyers",
      value: "116",
      delta: "+21% WoW",
      source: "Customers",
      insight: "Retention is still healthy under the acquisition spike.",
      x: 82,
      y: 12,
      tone: "up",
    },
    {
      group: "Customers",
      label: "New customer revenue",
      value: "GBP 11.2k",
      delta: "+53% WoW",
      source: "Orders + customers",
      insight: "TikTok is bringing buyers, not just traffic.",
      x: 88,
      y: 29,
      tone: "up",
    },
    {
      group: "Traffic",
      label: "Sessions",
      value: "12,640",
      delta: "+14% WoW",
      source: "ShopifyQL",
      insight: "Traffic lift is meaningful but smaller than revenue lift.",
      x: 58,
      y: 37,
      tone: "up",
    },
    {
      group: "Traffic",
      label: "Conversion rate",
      value: "2.47%",
      delta: "+0.42 pts",
      source: "ShopifyQL",
      insight: "The store converted the new demand better than last week.",
      x: 72,
      y: 43,
      tone: "up",
    },
    {
      group: "Traffic",
      label: "Add-to-cart rate",
      value: "7.8%",
      delta: "+1.1 pts",
      source: "ShopifyQL",
      insight: "Product-page intent improved around GlowPatch.",
      x: 89,
      y: 48,
      tone: "up",
    },
    {
      group: "Traffic",
      label: "Checkout started",
      value: "531",
      delta: "+24% WoW",
      source: "ShopifyQL",
      insight: "More buyers are entering checkout, not just browsing.",
      x: 78,
      y: 60,
      tone: "up",
    },
    {
      group: "Channels",
      label: "TikTok revenue",
      value: "GBP 5.9k",
      delta: "+166% WoW",
      source: "Referrers",
      insight: "The main breakout source.",
      x: 12,
      y: 70,
      tone: "up",
    },
    {
      group: "Channels",
      label: "TikTok new share",
      value: "31%",
      delta: "+19 pts",
      source: "Referrers",
      insight: "TikTok became the strongest discovery channel.",
      x: 26,
      y: 78,
      tone: "up",
    },
    {
      group: "Channels",
      label: "Instagram revenue",
      value: "GBP 4.7k",
      delta: "+27% WoW",
      source: "Referrers",
      insight: "Still a strong secondary creator channel.",
      x: 40,
      y: 72,
      tone: "up",
    },
    {
      group: "Channels",
      label: "Email revenue",
      value: "GBP 3.0k",
      delta: "+12% WoW",
      source: "Referrers",
      insight: "Good for existing buyers, weaker for discovery.",
      x: 56,
      y: 80,
      tone: "neutral",
    },
    {
      group: "Channels",
      label: "Meta ROAS",
      value: "0.85",
      delta: "-48% WoW",
      source: "Ad spend",
      insight: "The clearest channel to cut.",
      x: 72,
      y: 78,
      tone: "down",
    },
    {
      group: "Channels",
      label: "Meta spend",
      value: "GBP 520",
      delta: "GBP 440 rev",
      source: "Ad spend",
      insight: "Budget can be moved immediately.",
      x: 88,
      y: 72,
      tone: "down",
    },
    {
      group: "Products",
      label: "Top product",
      value: "GlowPatch",
      delta: "790 units",
      source: "Line items",
      insight: "The product carrying the week.",
      x: 18,
      y: 92,
      tone: "up",
    },
    {
      group: "Products",
      label: "GlowPatch revenue",
      value: "GBP 7.1k",
      delta: "+155% WoW",
      source: "Line items",
      insight: "A single SKU explains most of the spike.",
      x: 35,
      y: 90,
      tone: "up",
    },
    {
      group: "Products",
      label: "Product attach",
      value: "42%",
      delta: "+9 pts",
      source: "Line items",
      insight: "Cloud Cleanser is riding in GlowPatch baskets.",
      x: 50,
      y: 93,
      tone: "up",
    },
    {
      group: "Inventory",
      label: "GlowPatch stock",
      value: "410 left",
      delta: "0.5 weeks",
      source: "Products",
      insight: "Immediate stockout risk.",
      x: 65,
      y: 92,
      tone: "down",
    },
    {
      group: "Inventory",
      label: "Dead stock",
      value: "Mini Trio",
      delta: "510 units",
      source: "Products",
      insight: "Inventory exists but demand is zero.",
      x: 82,
      y: 90,
      tone: "down",
    },
    {
      group: "Operations",
      label: "Fulfilled orders",
      value: "286",
      delta: "92%",
      source: "Fulfillment",
      insight: "Ops are keeping up with the demand spike.",
      x: 9,
      y: 23,
      tone: "neutral",
    },
    {
      group: "Operations",
      label: "Unfulfilled orders",
      value: "26",
      delta: "+11 WoW",
      source: "Fulfillment",
      insight: "Watch this if GlowPatch keeps accelerating.",
      x: 8,
      y: 40,
      tone: "neutral",
    },
    {
      group: "Operations",
      label: "Shipping delay risk",
      value: "Medium",
      delta: "+2 days",
      source: "Fulfillment",
      insight: "Warehouse pressure is rising but not critical yet.",
      x: 91,
      y: 16,
      tone: "neutral",
    },
  ],
  synthetic_growth_brief: {
    week_of: "Week of 1 June 2026",
    headline_numbers: [
      { label: "Revenue", value: "GBP 18.4k, up 39% WoW", direction: "up" },
      { label: "Orders", value: "312, up 37% WoW", direction: "up" },
      { label: "Conversion", value: "2.47%, up from 2.05%", direction: "up" },
    ],
    whats_working:
      "TikTok organic created the breakout. It jumped from 12% to 31% of new customers and drove GBP 5.9k in revenue. GlowPatch Acne Dots are the product carrying the week: 790 units sold, GBP 7.1k revenue, and most high-volume orders came from TikTok clips.",
    what_to_cut:
      "Meta ads are the clean cut. They spent GBP 520 for GBP 440 revenue, only 7 orders, and just 3% of new customers. Keep that budget away from Meta until the TikTok stockout risk is handled.",
    one_move: {
      action: "Reorder GlowPatch today and move Meta's GBP 520 into TikTok creator seeding.",
      rationale:
        "GlowPatch has about half a week of stock left while TikTok is producing the best new-customer growth. If it sells out, the channel that just caused the revenue spike has nothing to sell.",
    },
  },
};
