-- Synapse — multi-source connectors
-- Adds: per-connection provider config + OAuth refresh tokens, a richer founder
-- business profile, and raw web-analytics events (Vercel drains push into this).

-- ── connections: generalise beyond Shopify ────────────────────────
alter table public.connections add column if not exists config jsonb not null default '{}'::jsonb;
alter table public.connections add column if not exists refresh_token text; -- ENCRYPT at rest (Vault/pgsodium)

-- Widen the provider set (was: shopify, stripe, ga4).
alter table public.connections drop constraint if exists connections_provider_check;
alter table public.connections add constraint connections_provider_check
  check (provider in ('shopify', 'stripe', 'ga4', 'vercel', 'website'));

-- For providers with no shop_domain (ga4/vercel/website), NULLs are distinct in a
-- normal unique index, which would allow duplicates — pin to one per founder+provider.
create unique index if not exists uniq_conn_founder_provider_null_shop
  on public.connections (founder_id, provider)
  where shop_domain is null;

-- ── founders: structured business profile from the website scraper ─
alter table public.founders add column if not exists business_profile jsonb;

-- ── analytics_events: raw web-analytics events (Vercel drain push) ─
create table if not exists public.analytics_events (
  id            bigint generated by default as identity primary key,
  connection_id uuid not null references public.connections (id) on delete cascade,
  event_type    text not null,          -- "pageview" | "event"
  path          text,
  referrer      text,                    -- origin / referring site
  session_id    text,
  device_id     text,
  occurred_at   timestamptz not null,
  raw           jsonb,
  created_at    timestamptz not null default now()
);
create index if not exists idx_events_connection_time
  on public.analytics_events (connection_id, occurred_at desc);

alter table public.analytics_events enable row level security;

-- Founders can read their own events (via the owning connection). Inserts come from
-- the Vercel drain endpoint using the service-role client, which bypasses RLS.
create policy "own analytics events" on public.analytics_events
  for all using (
    exists (
      select 1 from public.connections c
      where c.id = analytics_events.connection_id and c.founder_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from public.connections c
      where c.id = analytics_events.connection_id and c.founder_id = auth.uid()
    )
  );
